-- seed-protocol-definitions.sql
-- Industrial protocol definitions: Modbus, OPC-UA, MQTT, DNP3, BACnet
-- Run via: npx wrangler d1 execute haiphen_api --local --file=d1/seeds/seed-protocol-definitions.sql

INSERT OR REPLACE INTO network_protocol_definitions (protocol_id, name, description, default_port, function_codes_json, anomaly_rules_json) VALUES

-- Modbus TCP
('modbus', 'Modbus TCP', 'Industrial serial communication protocol for SCADA and PLC systems. Function codes define read/write operations on coils, discrete inputs, and registers.', 502,
'{"1":{"name":"Read Coils","description":"Read 1-2000 contiguous coil status","category":"read"},"2":{"name":"Read Discrete Inputs","description":"Read 1-2000 contiguous discrete input status","category":"read"},"3":{"name":"Read Holding Registers","description":"Read 1-125 contiguous holding registers","category":"read"},"4":{"name":"Read Input Registers","description":"Read 1-125 contiguous input registers","category":"read"},"5":{"name":"Write Single Coil","description":"Write a single coil to ON or OFF","category":"write"},"6":{"name":"Write Single Register","description":"Write a single holding register","category":"write"},"7":{"name":"Read Exception Status","description":"Read 8-bit exception status","category":"diagnostic"},"8":{"name":"Diagnostics","description":"Diagnostic subfunctions for serial line","category":"diagnostic"},"11":{"name":"Get Comm Event Counter","description":"Get communication event counter","category":"diagnostic"},"12":{"name":"Get Comm Event Log","description":"Get communication event log","category":"diagnostic"},"15":{"name":"Write Multiple Coils","description":"Write 1-1968 contiguous coils","category":"write"},"16":{"name":"Write Multiple Registers","description":"Write 1-123 contiguous registers","category":"write"},"43":{"name":"Read Device Identification","description":"Read device identification objects","category":"diagnostic"}}',
'[{"rule":"unknown_function_code","description":"Function code not in standard Modbus specification","severity":"high"},{"rule":"write_to_readonly","description":"Write attempt to read-only input registers (FC 1-4 address space)","severity":"high"},{"rule":"oversized_payload","description":"Payload exceeds maximum ADU size of 260 bytes","severity":"medium"},{"rule":"broadcast_write","description":"Write operation sent to broadcast address (unit 0)","severity":"high"},{"rule":"rapid_polling","description":"Read requests exceeding 10 per second to same register","severity":"medium"},{"rule":"exception_flood","description":"More than 5 exception responses in 10 seconds","severity":"medium"},{"rule":"register_scan","description":"Sequential read of non-contiguous register blocks (reconnaissance pattern)","severity":"high"},{"rule":"timing_jitter","description":"Response time deviation exceeds 3x baseline average","severity":"low"}]'),

-- OPC-UA
('opcua', 'OPC UA', 'Open Platform Communications Unified Architecture. Secure, reliable, platform-independent standard for industrial data exchange. Supports discovery, sessions, subscriptions, and method calls.', 4840,
'{"1":{"name":"FindServers","description":"Discover OPC UA servers on the network","category":"discovery"},"2":{"name":"GetEndpoints","description":"Get available endpoints and security policies","category":"discovery"},"3":{"name":"CreateSession","description":"Create a new OPC UA session","category":"session"},"4":{"name":"ActivateSession","description":"Activate a created session with credentials","category":"session"},"5":{"name":"CloseSession","description":"Close an active session","category":"session"},"6":{"name":"Browse","description":"Browse the server address space","category":"read"},"7":{"name":"BrowseNext","description":"Continue a browse operation","category":"read"},"8":{"name":"Read","description":"Read attribute values from nodes","category":"read"},"9":{"name":"Write","description":"Write attribute values to nodes","category":"write"},"10":{"name":"Call","description":"Call a method on a server object","category":"write"},"11":{"name":"CreateSubscription","description":"Create a subscription for monitored items","category":"subscribe"},"12":{"name":"CreateMonitoredItems","description":"Add items to a subscription","category":"subscribe"},"13":{"name":"Publish","description":"Request notification messages","category":"subscribe"},"14":{"name":"TranslateBrowsePathsToNodeIds","description":"Translate browse paths to node IDs","category":"read"}}',
'[{"rule":"no_security","description":"Session established without security mode (None)","severity":"critical"},{"rule":"anonymous_auth","description":"Anonymous authentication used on production server","severity":"high"},{"rule":"certificate_expired","description":"Client or server certificate has expired","severity":"high"},{"rule":"unknown_node_access","description":"Access to node IDs outside expected namespace","severity":"medium"},{"rule":"method_call_unauthorized","description":"Method call attempt by user without ExecutableByUser privilege","severity":"high"},{"rule":"session_hijack","description":"Session reactivation from different endpoint","severity":"critical"},{"rule":"address_space_scan","description":"Exhaustive browse of server namespace (reconnaissance)","severity":"high"},{"rule":"rapid_write","description":"Write operations exceeding 50 per second","severity":"medium"}]'),

-- MQTT
('mqtt', 'MQTT', 'Message Queuing Telemetry Transport. Lightweight publish/subscribe messaging protocol designed for IoT and constrained devices. Supports QoS levels 0-2 and retained messages.', 1883,
'{"1":{"name":"CONNECT","description":"Client requests connection to broker","category":"session"},"2":{"name":"CONNACK","description":"Broker acknowledges connection","category":"session"},"3":{"name":"PUBLISH","description":"Publish message to topic","category":"write"},"4":{"name":"PUBACK","description":"Acknowledge QoS 1 publish","category":"ack"},"5":{"name":"PUBREC","description":"Publish received (QoS 2 part 1)","category":"ack"},"6":{"name":"PUBREL","description":"Publish release (QoS 2 part 2)","category":"ack"},"7":{"name":"PUBCOMP","description":"Publish complete (QoS 2 part 3)","category":"ack"},"8":{"name":"SUBSCRIBE","description":"Subscribe to topics","category":"subscribe"},"9":{"name":"SUBACK","description":"Acknowledge subscription","category":"ack"},"10":{"name":"UNSUBSCRIBE","description":"Unsubscribe from topics","category":"subscribe"},"11":{"name":"UNSUBACK","description":"Acknowledge unsubscription","category":"ack"},"12":{"name":"PINGREQ","description":"Ping request (keepalive)","category":"diagnostic"},"13":{"name":"PINGRESP","description":"Ping response","category":"diagnostic"},"14":{"name":"DISCONNECT","description":"Client disconnection","category":"session"}}',
'[{"rule":"no_auth","description":"CONNECT without username/password on secured broker","severity":"critical"},{"rule":"wildcard_subscribe","description":"Subscription to # (all topics) wildcard","severity":"high"},{"rule":"sys_topic_access","description":"Subscription to $SYS/# broker internal topics","severity":"medium"},{"rule":"retained_overwrite","description":"Retained message overwrite on critical control topic","severity":"high"},{"rule":"qos0_control","description":"Control command published with QoS 0 (no delivery guarantee)","severity":"medium"},{"rule":"oversized_payload","description":"Payload exceeds configured maximum packet size","severity":"medium"},{"rule":"topic_injection","description":"Topic contains path traversal or injection characters","severity":"high"},{"rule":"rapid_connect","description":"Multiple CONNECT attempts from same client ID (brute force)","severity":"high"}]'),

-- DNP3
('dnp3', 'DNP3', 'Distributed Network Protocol 3. Primarily used in SCADA systems for communication between control centers and remote terminal units (RTUs). Supports event-based reporting and time synchronization.', 20000,
'{"1":{"name":"Read","description":"Read data objects from outstation","category":"read"},"2":{"name":"Write","description":"Write data objects to outstation","category":"write"},"3":{"name":"Select","description":"Select an output point for operation","category":"write"},"4":{"name":"Operate","description":"Operate a previously selected output point","category":"write"},"5":{"name":"Direct Operate","description":"Operate output without prior select","category":"write"},"6":{"name":"Direct Operate No Ack","description":"Operate without acknowledgment","category":"write"},"7":{"name":"Freeze","description":"Freeze counter values","category":"write"},"8":{"name":"Freeze No Ack","description":"Freeze counters without acknowledgment","category":"write"},"9":{"name":"Freeze and Clear","description":"Freeze and clear counter values","category":"write"},"13":{"name":"Cold Restart","description":"Perform cold restart of outstation","category":"control"},"14":{"name":"Warm Restart","description":"Perform warm restart of outstation","category":"control"},"20":{"name":"Enable Unsolicited","description":"Enable unsolicited responses","category":"config"},"21":{"name":"Disable Unsolicited","description":"Disable unsolicited responses","category":"config"},"23":{"name":"Delay Measurement","description":"Measure communication delay","category":"diagnostic"}}',
'[{"rule":"cold_restart","description":"Cold restart command issued (FC 13)","severity":"critical"},{"rule":"warm_restart","description":"Warm restart command issued (FC 14)","severity":"high"},{"rule":"direct_operate_no_ack","description":"Direct operate without acknowledgment (FC 6) on critical point","severity":"high"},{"rule":"unsolicited_disable","description":"Unsolicited responses disabled (FC 21)","severity":"medium"},{"rule":"unauthorized_write","description":"Write to configuration objects without proper authentication","severity":"critical"},{"rule":"sequence_mismatch","description":"Application layer sequence number mismatch","severity":"medium"},{"rule":"broadcast_control","description":"Control command sent to broadcast address","severity":"critical"},{"rule":"timing_attack","description":"Delay measurement values outside expected range","severity":"medium"}]'),

-- BACnet
('bacnet', 'BACnet', 'Building Automation and Control Networks protocol. Standard for building management systems (HVAC, lighting, fire, access control). Supports object-based device modeling with standardized services.', 47808,
'{"1":{"name":"Who-Is","description":"Discover BACnet devices on the network","category":"discovery"},"2":{"name":"I-Am","description":"Device identification response","category":"discovery"},"3":{"name":"Who-Has","description":"Find device with specific object","category":"discovery"},"4":{"name":"I-Have","description":"Response to Who-Has","category":"discovery"},"5":{"name":"ReadProperty","description":"Read a property from an object","category":"read"},"6":{"name":"ReadPropertyMultiple","description":"Read multiple properties at once","category":"read"},"7":{"name":"WriteProperty","description":"Write a value to an object property","category":"write"},"8":{"name":"WritePropertyMultiple","description":"Write multiple properties at once","category":"write"},"9":{"name":"SubscribeCOV","description":"Subscribe to Change of Value notifications","category":"subscribe"},"10":{"name":"COVNotification","description":"Change of Value notification","category":"subscribe"},"11":{"name":"CreateObject","description":"Create a new BACnet object","category":"write"},"12":{"name":"DeleteObject","description":"Delete a BACnet object","category":"write"},"13":{"name":"ReinitializeDevice","description":"Reinitialize or reboot device","category":"control"},"14":{"name":"DeviceCommunicationControl","description":"Enable or disable device communication","category":"control"}}',
'[{"rule":"reinitialize_device","description":"ReinitializeDevice service invoked (potential disruption)","severity":"critical"},{"rule":"comm_control_disable","description":"DeviceCommunicationControl used to disable communication","severity":"critical"},{"rule":"write_setpoint","description":"WriteProperty to critical HVAC setpoint outside safe range","severity":"high"},{"rule":"object_deletion","description":"DeleteObject on operational BACnet object","severity":"high"},{"rule":"foreign_device","description":"Unregistered foreign device communication via BBMD","severity":"medium"},{"rule":"who_is_scan","description":"Rapid Who-Is broadcast (network reconnaissance)","severity":"medium"},{"rule":"no_auth_write","description":"WriteProperty without application-layer authentication","severity":"high"},{"rule":"schedule_override","description":"Modification to BACnet Schedule objects outside maintenance window","severity":"medium"}]'),

-- EtherNet/IP
('ethernetip', 'EtherNet/IP', 'EtherNet/Industrial Protocol. Uses Common Industrial Protocol (CIP) over standard Ethernet for industrial automation. Supports implicit (real-time I/O) and explicit messaging.', 44818,
'{"1":{"name":"List Services","description":"List communication services supported","category":"discovery"},"2":{"name":"List Identity","description":"Get device identity information","category":"discovery"},"3":{"name":"List Interfaces","description":"List network interfaces","category":"discovery"},"4":{"name":"Register Session","description":"Register a CIP session","category":"session"},"5":{"name":"Unregister Session","description":"Close a CIP session","category":"session"},"6":{"name":"Send RR Data","description":"Send request/reply data (explicit messaging)","category":"read"},"7":{"name":"Send Unit Data","description":"Send connected data (implicit messaging)","category":"write"},"8":{"name":"Get Attribute Single","description":"Read a single attribute from CIP object","category":"read"},"9":{"name":"Set Attribute Single","description":"Write a single attribute to CIP object","category":"write"},"10":{"name":"Reset","description":"Reset CIP device","category":"control"},"11":{"name":"Forward Open","description":"Establish CIP connection","category":"session"},"12":{"name":"Forward Close","description":"Close CIP connection","category":"session"}}',
'[{"rule":"reset_command","description":"CIP Reset service invoked on production device","severity":"critical"},{"rule":"firmware_update","description":"Firmware update initiated over EtherNet/IP","severity":"high"},{"rule":"session_flood","description":"Excessive Register Session requests (connection exhaustion)","severity":"high"},{"rule":"unconnected_write","description":"Write via unconnected messaging bypassing session security","severity":"high"},{"rule":"identity_scan","description":"Rapid List Identity broadcast (network reconnaissance)","severity":"medium"},{"rule":"implicit_config_change","description":"Configuration change via implicit I/O connection","severity":"medium"},{"rule":"trusted_slot_bypass","description":"CIP routing through non-trusted backplane slot","severity":"critical"},{"rule":"class3_timeout","description":"Connected messaging timeout indicating network issues","severity":"low"}]');
